### ISSUE TITLE
Check the minimum spindle RPM requested is above the spindle minimum speed

### ISSUE THREAD

**Issue by jaysuk** [MillenniumMachines/MillenniumOS#129]
In M3.9, there is a check the spindle RPM is less than the maximum RPM for the spindle being used. 
https://github.com/MillenniumMachines/MillenniumOS/blob/f4629caeeea408c15e686ac8cbd3380a6eab83a1/macro/machine/M3.9.g#L27
There is a not a check that the requested spindle RPM is greater than the minimum for the spindle being used.

**Comment by benagricola** [comment]
Fixed by #134
