### ISSUE TITLE
Let us Skip tool offset re-probe

### ISSUE THREAD

**Issue by DeadspaceDan** [MillenniumMachines/MillenniumOS#149]
If I am running toolpaths individually rather than batch processing them, I frequently have the same tool. It currently asks me to set the tool height using the toolsetter every time. 

Please give a prompt when you ask for a tool change to keep the last offset and not require toolsetter touch off again if I haven’t changed tools. 

Oops sorry wrong label.

**Comment by benagricola** [comment]
Fixed by #163
