### ISSUE TITLE
wizard: Make sure features are explained before or when they are asked to be enabled

### ISSUE THREAD

**Issue by bdistin** [MillenniumMachines/MillenniumOS#166]
During Mandic Labs stream, when prompted to enable the Spindle Feedback feature, he had no idea what it was and just enabled it. I don't think he had any wiring back to General IO to receive the feedback, and I suppose it may have solved itself, but this sort of thing could be problematic. I also suppose it's not necessarily clear to a new user that the highlighted blue button is the recommended option.

**Comment by benagricola** [comment]
Thanks @bdistin - fixed by #175 - please create new issues for anything similar to this :+1:
